---
- name: Install emacs
  become: yes
  package:
    name: emacs
    state: present

- name: Delete existing emacs.d
  file:
    path: "{{ ansible_env.HOME }}/.emacs.d"
    state: absent

- name: Clone emacs.d
  git:
    repo: git@github.com:jmhelt/emacs.d.git
    dest: "{{ ansible_env.HOME }}/.emacs.d"
    update: yes
